@echo off
SETLOCAL
if not exist EZ-BatchHash_%~n0.csv goto makecsv
if exist EZ-BatchHash_%~n0.csv goto appendcsv
:makecsv
echo File,Bytes,MD5,%~dp1,,,,,,,,,Generated by: https://github.com/horusra/EZ-BatchHash/>EZ-BatchHash_%~n0.csv
:appendcsv
for /f "tokens=*" %%a in ('certutil -hashfile %1 %~n0 ^| findstr /V "hash successfully"') do set fin=%%a
(echo "%~nx1",%~z1,%fin%,)>>EZ-BatchHash_%~n0.csv
(echo %fin%	*%~nx1)>>EZ-BatchHash_%~n0.txt
echo %fin%|clip
exit